### PR TITLE
CRA_update

### PR DESCRIPTION
**Pull request by jkhartshorne**
This should work with the current version of the CLI and this version of exptemplates-basic: https://github.com/pushkin-consortium/pushkin-exptemplates-basic/pull/32

### CODE REVIEW

**Comment by jkhartshorne** [comment]
To test this, you'll need this branch pulled locally, as well as the to-be-merged branch from https://github.com/pushkin-consortium/pushkin-exptemplates-basic/pull/32. You'll also need the latest unpublished version of the CLI.

Make sure your Docker is clean. `pushkin armageddon` will work if needed.

Go to pushkin-cli and run 

`> yarn build`
`> cd ..`
`> mkdir temp`
`> cd temp`
`> node ../pushkin-cli/build/index.js install site`

Select `path` from the options and then enter the absolute path to wherever you have pulled this branch of the site template. For me, that is `/Users/jkhartshorne/Documents/Projects/PushkinDev/PushkinNew/pushkin-sitetemplates-basic`. It'll be something else for you.

Assuming that works, run

`> node ../pushkin-cli/build/index.js install experiment`

Again, choose the `path` option and enter the absolute path to wherever you have the to-be-tested branch of the basic experiment template.

Assuming that works, run

`> node ../pushkin-cli/build/index.js prep`
`> node ../pushkin-cli/build/index.js start`

When it says it is ready, open a browser and navigate to `localhost`. Make sure that not only does the website load, but that you can run the experiment. The experiment should just display "hello world". If you click or press a key, it'll thank you for completing the experiment.

If all that works for you, please approve!

**Comment by jessestorbeck** [comment]
Everything works!

**Review by jessestorbeck — APPROVED** [review]
I followed the instructions and was able to view the site on localhost and run the experiment.

**Comment by jkhartshorne** [comment]
Great! I'd like @hzeng2 to confirm that it works for her, too, before I merge.

**Comment by hzeng2** [comment]
@jkhartshorne -- I couldn't get through the absolute path step. Here is what I did:
- checkout and pull the pushkin-cli/master branch
- checkout and pull the pushkin-sitetemplate-basic/CRA_update branch
- checkout and pull the pushkin-exptemplates-basic/webpackv5 branch
- run `docker info` and get `Server: Containers: 1 Running: 1`
- then followed these steps:
>Go to pushkin-cli and run

> yarn build
> cd ..
> mkdir temp
> cd temp
> node ../pushkin-cli/build/index.js install site

> Select path from the options and then enter the absolute path to wherever you have pulled this branch of the site template. 

After I put in the path, I got:

> retrieving from ../pushkin-sitetemplates-basic
> be patient...
> failed to copy pushkin site template: TypeError: _fs.default.cpSync is not a function
> (node:11731) UnhandledPromiseRejectionWarning: TypeError: _fs.default.cpSync is not a function
>     at _callee4$ (/home/haozeng/pushkin-cli/build/commands/sites/index.js:324:28)
>     at tryCatch (/home/haozeng/pushkin-cli/node_modules/regenerator-runtime/runtime.js:45:40)
>     at Generator.invoke [as _invoke] (/home/haozeng/pushkin-cli/node_modules/regenerator-runtime/runtime.js:274:22)
>     at Generator.prototype.<computed> [as next] (/home/haozeng/pushkin-cli/node_modules/regenerator-runtime/runtime.js:97:21)
>     at asyncGeneratorStep (/home/haozeng/pushkin-cli/build/commands/sites/index.js:41:103)
>     at _next (/home/haozeng/pushkin-cli/build/commands/sites/index.js:43:194)
>     at /home/haozeng/pushkin-cli/build/commands/sites/index.js:43:364
>     at new Promise (<anonymous>)
>     at /home/haozeng/pushkin-cli/build/commands/sites/index.js:43:97
>     at _copyPushkinSite (/home/haozeng/pushkin-cli/build/commands/sites/index.js:371:27)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:11731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
> (node:11731) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Did I miss any steps or run any steps wrong?

**Comment by jkhartshorne** [comment]
@hzeng2 -- can you please paste in what you were using for the absolute path? This output:

`retrieving from ../pushkin-sitetemplates-basic`

suggests to me that maybe you used a relative path. Can you please double-check?

**Comment by jessestorbeck** [comment]
Not sure if it matters, but I did run `yarn install` before `yarn build` based on our experience with this issue pushkin-consortium/pushkin#195.

**Comment by hzeng2** [comment]
Good call! I actually didn't input the absolute path before. I googled and used `pwd` to retrieve absolute path. It's `/home/haozeng/pushkin-sitetemplate-basic`. I also ran `yarn install` before `yarn build`. However, I am still stuck in the same place:

> retrieving from /home/haozeng/pushkin-sitetemplate-basic
be patient...
failed to copy pushkin site template: TypeError: _fs.default.cpSync is not a function
(node:16459) UnhandledPromiseRejectionWarning: TypeError: _fs.default.cpSync is not a function
    at _callee4$ (/home/haozeng/pushkin-cli/build/commands/sites/index.js:324:28)
    at tryCatch (/home/haozeng/pushkin-cli/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/haozeng/pushkin-cli/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/home/haozeng/pushkin-cli/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/haozeng/pushkin-cli/build/commands/sites/index.js:41:103)
    at _next (/home/haozeng/pushkin-cli/build/commands/sites/index.js:43:194)
    at /home/haozeng/pushkin-cli/build/commands/sites/index.js:43:364
    at new Promise (<anonymous>)
    at /home/haozeng/pushkin-cli/build/commands/sites/index.js:43:97
    at _copyPushkinSite (/home/haozeng/pushkin-cli/build/commands/sites/index.js:371:27)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16459) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:16459) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jkhartshorne** [comment]
@hzeng2 -- did you try Jesse's suggestion of `yarn install` and then `yarn build`? 

I'm a little puzzled by the error message and am hoping it is that.

**Comment by hzeng2** [comment]
@jkhartshorne -- Yes, adding `yarn install` and inputting the absolute path. Then I got the same error messages.

**Comment by jkhartshorne** [comment]
@hzeng2 -- what version of Node are you running? I recommend Node 20.2.

**Comment by hzeng2** [comment]
@jkhartshorne -- I was using node 14.xxx before. I switched to 20.2. Now I got to `node ../pushkin-cli/build/index.js prep`. However, it just keeps printing out `...`:

> 13:57 $ node ../pushkin-cli/build/index.js prep
Removing any .DS_Store files, if present.
package manager:  yarn
resetting experiments.js
Started prepping API for test
Started loading API controller for test
Using build-if-changed for  test_api
Installing dependencies for /home/haozeng/temp/experiments/test/api controllers
Started prepping web page for test
Started loading web page for test
Using build-if-changed for  test_web
Installing dependencies for /home/haozeng/temp/experiments/test/web page
loaded docker-compose.dev.yml and pushkin.yaml.
Building worker for test
Building docker image for test_worker
userMigsDir: /home/haozeng/temp/users/migrations
userDatabase: localtestdb
Loading migrations for test
Updated users/config.yaml to be compatible with default site template v2+.
expConfig:
 {"experimentName":"test","shortName":"test","apiControllers":{"mountPath":"test","location":"api controllers","name":"mycontroller"},"worker":{"location":"worker","service":{"image":"test","links":["message-queue","test_db"],"environment":{"AMQP_ADDRESS":"amqp://message-queue:5672","DB_USER":"postgres","DB_PASS":"example","DB_URL":"test_db","DB_NAME":"test_db"}}},"webPage":{"location":"web page"},"migrations":{"location":"migrations"},"seeds":{"location":""},"database":"localtestdb","logo":"logo512.png","text":"Enter your experiment description here.","tagline":"Be a citizen scientist! Try this quiz.","duration":"","productionDB":"Main"}
Waiting for database to start...
...
Building test_api from /home/haozeng/temp/experiments/test/api controllers
Building test_web from /home/haozeng/temp/experiments/test/web page
...
test_api is built
test_api is published locally via yalc
test_web is built
test_web is published locally via yalc
Loaded web page for test (test_web)
Added test to experiments.js
Writing out experiments.js
Installing combined API
Installed combined API
Installing combined front-end
Installed combined front-end
...
...
...
...
...
...
...
...
...
...
Finished building all experiment workers
updating docker-compose.dev.yml
Writing out front-end config
...
...
...
...
...
...

**Comment by hzeng2** [comment]
@jkhartshorne -- Never mind! I control+c to exit the non-ending `...` and ran `node ../pushkin-cli/build/index.js start` anyway. It worked! I could click "play now" under the experiment I named and saw "hello world!" and pressed any key to see the thank you message.

**Pull request merged**
